### ISSUE TITLE
createShieldCode.js fails to return the ID; states undefined

### ISSUE THREAD

**Issue by MaeveOReilly** [IBM-Bluemix/iot4i-api-examples-nodejs#2]
When I run this I get a typo (succesfully != successfully) and an undefined: 

C:\Users\IBM_ADMIN\git\iot4i-api-examples-nodejs>node createShieldCode.js
Using the /shieldcode REST endpoint to create a new shield code...
**Succesfully** created shield code **undefined**
'OK'

It does read it back so might actually be OK: 

C:\Users\IBM_ADMIN\git\iot4i-api-examples-nodejs>node readShieldCode.js
Using the /jscode/byuuid/ REST endpoint to obtain information about a shield cod
e...
Using URL https://iot4insurance-api-719e2c7d-efef-4046-883a-2a0e280ea40d.eu-gb.m
ybluemix.net/jscode/byuuid/1
'var WATER_LEAK_SHIELD_NAME = "waterLeakShield";\nvar WATER_LEAK_SHIELD_DELAY =
20000;\nvar WATER_LEAK_SHIELD_UUID = 1;\nvar waterLeakSafelet = function(payload
) {\n\treturn (JSON.parse(payload.liquid_detected));\n};\nvar  waterLeakEntryCon
dition = function(payload) {\n\treturn (payload.liquid_detected);\n};\nvar water
LeakMessage = function(payload) {\n\tpayload.extra = payload.extra || {};\n\tpay
load.extra.isHandled = false;\n\tpayload.extra.urgent = true;\n\tpayload.extra.l
ocationDesc = "Living Room";\n\tpayload.extra.deviceDesc = "leakSmart Sensor";\n
\treturn (constructMessage(payload, WATER_LEAK_SHIELD_UUID, \'WaterLeakHazard\',
 \'A water leak detected!\'));\n};\nvar waterLeakShield = function(payload){\n\t
var shield = getShieldByName(WATER_LEAK_SHIELD_NAME);\n\treturn (commonShield(pa
yload, shield));\n};\nregisterShield(WATER_LEAK_SHIELD_UUID, WATER_LEAK_SHIELD_N
AME, waterLeakEntryCondition, undefined, waterLeakSafelet, waterLeakMessage, WAT
ER_LEAK_SHIELD_DELAY);\n'

**Comment by MaeveOReilly** [comment]
Looks like we just need to change console.log("Succesfully created shield code " + shieldCode.shieldUUID); (from shieldCode.id).  I will try to do this.  And fix the typo.

**Comment by dragos-cojocari** [comment]
Fixed. Good catch.
